name: my_template
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.7+26

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  logger: ^2.6.2
  dio: ^5.9.0
  get_it: ^9.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_bloc: ^9.1.1
  iconly: ^1.0.1
  smooth_page_indicator: ^2.0.1
  flutter_svg: ^2.2.3
  svg_image_provider: ^0.1.1
  dashed_progress_bar: ^0.0.1
  internet_connection_checker_plus: ^2.9.1+2
  google_nav_bar: ^5.0.7
  line_icons: ^2.0.3
  skeletonizer: ^2.1.2
  flutter_rating: ^2.0.2
  intl: ^0.20.2
  my_progress_bar: ^2.1.0
  confetti: ^0.8.0
  dotted_border: ^3.1.0
  family_bottom_sheet: ^0.1.0
  lottie: ^3.3.2
  carousel_slider: ^5.1.2
  #  turnable_page: ^1.0.1  # Book swiper effect # conflicts with SDK
  camera: ^0.11.0
  permission_handler: ^11.3.1

  # app localization
  flutter_localizations:
    sdk: flutter

  shared_preferences: ^2.5.4
  auto_size_text: ^3.0.0
  turn_page_transition: ^0.5.0 # best option for now # open book
  #  device_preview: ^1.3.1 # not used
  webview_flutter: ^4.13.1
  another_flushbar: ^1.12.32
  flutter_html: ^3.0.0
  connectivity_plus: ^7.0.0
  video_player: ^2.11.1
  change_app_package_name: ^1.5.0
  open_filex: ^4.7.0
  path_provider: ^2.1.5
  flutter_staggered_grid_view: ^0.7.0
  equatable: ^2.0.8
  web_socket_channel: ^3.0.3
  #  scroll_to_hide: ^2.2.1 # not used
  image_picker: ^1.2.1
  file_picker: ^10.2.0
  image: ^4.8.0
  custom_refresh_indicator: ^4.0.1
  intl_phone_field: ^3.2.0
  #  marquee: ^2.3.0 # not using
  qr_code_scanner_plus: ^2.1.2
  myid: ^3.1.44
  url_launcher: ^6.2.0
  flutter_remix: ^0.0.3
  google_sign_in: ^7.1.0
  sign_in_with_apple: ^6.1.4



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/onboarding_images/
    - assets/images/
    - assets/home_page/
    - assets/animation/
    - assets/temp_images/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
